name: deploy raillo raillo-frontend

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # 최신 Next.js 호환
          cache: npm          #  npm 캐시 사용

      - name: Install & Build & Export
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          npm ci                        # lock 파일 기반 설치
          npm run build
          npm run export

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm s3://raillo-frontend --recursive
          aws s3 cp --recursive --region ap-northeast-2 ./out s3://raillo-frontend

      - name: Clear Cache to Cloudfront
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws cloudfront create-invalidation --distribution-id E3EVY7JHHX1RQX --paths "/*"
